#%%
import requests
import urllib.parse

#%%
tree_name_mapping = {
    "Lophostemon confertus": "brush box",
    "Platanus acerifolia": "London plane",
    "Melaleuca quinquenervia": "bottle brush tree",
    "Tristaniopsis laurina": "",
    "Robinia pseudoacacia Frisia": "",
    "Jacaranda mimosifolia": "",
    "Corymbia maculata": "",
    "Cupaniopsis anacardioides": "",
    "Elaeocarpus reticulatus": "",
    "Callistemon viminalis": "",
    "Ficus microcarpa var hillii": "",
    "Pistacia chinensis": "",
    "Fraxinus griffithii": "",
    "Sapium sebiferum": "",
    "Liquidambar styraciflua": "",
    "Lagerstroemia indica": "",
    "Eucalyptus microcorys": "",
    "Flindersia australis": "",
    "Celtis australis": "",
    "Populus simonii": "",
    "Koelreuteria paniculata": "",
    "Fraxinus pennsylvanica": "",
    "Angophora costata": "",
    "Platanus orientalis Digitata": "",
    "Eucalyptus sideroxylon": "",
    "Ulmus parvifolia": "",
    "Livistona australis": "",
    "Corymbia citriodora": "",
    "Magnolia grandiflora": "",
    "Populus nigra Italica": "",
    "Eucalyptus sp.": "",
    "Eucalyptus botryoides": "",
    "Fraxinus oxycarpa Raywoodii": "",
    "Ficus benjamina": "",
    "Eucalyptus scoparia": "",
    "Liriodendron tulipifera": "",
    "Ficus rubiginosa": "",
    "Olea europaea subsp europaea": "",
    "Celtis occidentalis": "",
    "Platanus orientalis": "",
    "Waterhousea floribunda": "",
    "Callistemon salignus": "",
    "Brachychiton acerifolius": "",
    "Syzygium paniculatum": "",
    "Harpephyllum caffrum": "",
    "Casuarina cunninghamiana": "",
    "Melaleuca styphelioides": "",
    "Populus deltoides": "",
    "Banksia integrifolia": "",
    "Casuarina glauca": "",
    "Hymenosporum flavum": "",
    "Corymbia eximia": "",
    "Stenocarpus sinuatus": "",
    "Glochidion ferdinandii": "",
    "Acacia binervia": "",
    "Agonis flexuosa": "",
    "Waterhousea flori. 'Green Ave'": "",
    "Syzygium luehmannii": "",
    "Backhousia citriodora": "",
    "Gleditsia trican Sunburst": "",
    "Eucalyptus saligna": "",
    "Castanospermum australe": "",
    "Pittosporum rhombifolium": "",
    "Pyrus calleryana": "",
    "Schinus molle": "",
    "Acer negundo": "",
    "Robinia pseudoacacia": "",
    "Acer Buergeranum": "",
    "Acmena smithii": "",
    "Melaleuca armillaris": "",
    "Washingtonia robusta": "",
    "Callistemon citrinus": "",
    "Podocarpus elatus": "",
    "Cinnamomum camphora": "",
    "Casuarina sp.": "",
    "Gleditsia trican Shademaster": "",
    "Eucalyptus robusta": "",
    "Eucalyptus nicholii": "",
    "Quercus palustris": "",
    "Harpulia pendula": "",
    "Brachychiton discolor": "",
    "Fraxinus sp.": "",
    "Cyathea cooperi": "",
    "Koelreuteria elegans subsp For": "",
    "Grevillea robusta": "",
    "Melaleuca linariifolia": "",
    "Plumeria acutifolia": "",
    "Olea africana": "",
    "Melia azedarach": "",
    "Murraya paniculata": "",
    "Leptospermum sp.": "",
    "Ginkgo biloba": "",
    "Phoenix canariensis": "",
    "Syzygium australe": "",
    "Syagrus romanzoffianum": "",
    "Platanus occidentalis": "",
    "Callistemon sp.": "",
    "Metrosideros excelsa": "",
    "Archontophoenix cunninghamiana": "",
    "Archontophoenix alexandrae": "",
    "Lagunaria patersonii": "",
    "Populus x canadensis": "",
    "Hibiscus tiliaceus": "",
    "Prunus sp.": "",
    "Eucalyptus grandis": "",
    "Agathis robusta": "",
    "Fraxinus angustifolia": "",
    "Grevillea sp.": "",
    "Tristaniopsis 'Luscious'": "",
    "Unknown": "",
    "Araucaria cunninghamii": "",
    "Syzygium sp.": "",
    "Corymbia ficifolia": "",
    "Macadamia integrifolia": "",
    "Persea americana": "",
    "Afrocarpus Falcatus": "",
    "Zelkova serrata 'Green Vase'": "",
    "Schefflera actinophylla": "",
    "Pyrus ussuriensis": "",
    "Pittosporum sp.": "",
    "Leptospermum citratum": "",
    "Fraxinus excelsior": "",
    "Brachychiton sp.": "",
    "Eucalyptus crebra": "",
    "Quercus ilex": "",
    "Celtis sinensis": "",
    "Elaeocarpus eumundii": "",
    "Acer sp.": "",
    "Gordonia axillaris": "",
    "Prunus x blireana": "",
    "Citrus sp": "",
    "Schefflera sp": "",
    "Citharexylum spinosum": "",
    "Cupressus sp.": "",
    "Alectryon excelsum": "",
    "Bizmarckia nobilis": "",
    "Eucalyptus sideroxylon Rosea": "",
    "Eucalyptus punctata": "",
    "Alectryon subcinereus": "",
    "Bauhinia variegata": "",
    "Camellia sp": "",
    "Ficus macrophylla": "",
    "Populus simonii Fastigiata": "",
    "Citrus limon": "",
    "Hibiscus rosa sinensis": "",
    "Melaleuca sp.": "",
    "Brachychiton populneus": "",
    "Podocarpus Falcatus": "",
    "Leptospermum laevigatum": "",
    "Pittosporum undulatum": "",
    "Platanus insularis": "",
    "Ulmus sp.": "",
    "Acer platanoides": "",
    "Alnus sp.": "",
    "Populus alba": "",
    "Hibiscus syriascus": "",
    "Angophora floribunda": "",
    "Leptospermum petersonii": "",
    "Dypsis lutescens": "",
    "Camellia japonica": "",
    "Eriobotrya japonica": "",
    "Howea forsteriana": "",
    "Banksia serrata": "",
    "Nyssa sylvatica": "",
    "Photinia robusta": "",
    "Mag. grandiflora 'Little Gem'": "",
    "Chamaecyparis obtusa 'Crippsii": "",
    "Celtis sp.": "",
    "Platanus acerifolia 'Bloodgood": "",
    "Acacia sp.": "",
    "Olea europea var. africana": "",
    "Eucalyptus globulus ssp. bicos": "",
    "Eucalyptus gummifera": "",
    "Murraya sp": "",
    "Cupressus sempervirens": "",
    "Chamaecyparis lawsoniana": "",
    "Albizia lophantha": "",
    "Strelitzia nicolai": "",
    "Ficus sp.": "",
    "Allocasuarina littoralis": "",
    "Prunus cerasifera Nigra": "",
    "Populus yunnanensis": "",
    "Allocasuarina torulosa": "",
    "Melaleuca bracteata": "",
    "Washingtonia filifera": "",
    "Photinia serrulata": "",
    "Alectryon tomentosus": "",
    "Howea belmoreana": "",
    "Pittosporum eugenioides": "",
    "Mangifera sp.": "",
    "Cotinous coggygria": "",
    "Hakea sp.": "",
    "Eucalyptus globulus": "",
    "Alnus jorullensis": "",
    "Catalpa bignonoides": "",
    "Butia capitata": "",
    "Rose sp.": "",
    "Araucaria heterophylla": "",
    "Allocasuarina cunninghamiana": "",
    "Cordyline australis": "",
    "Palm sp.": "",
    "Ulmus glabra Lutescens": "",
    "Eucalyptus bicostata": "",
    "Strelitzia sp.": "",
    "Eucalyptus melliodora": "",
    "Eucalyptus ficifolia": "",
    "Pyrus calleryana 'Chanticleer'": "",
    "Phoenix roebelenii": "",
    "Araucaria columnaris": "",
    "Acacia baileyana": "",
    "Eucalyptus mannifera": "",
    "Nerium oleander": "",
    "Viburnum tinus": "",
    "Eucalyptus saligna x botryoid": "",
    "Populus alba Pyramidalis": "",
    "Duranta erecta": "",
    "Ficus carica": "",
    "Liquidambar formosana": "",
    "Magnolia sp.": "",
    "Populus sp.": "",
    "Lophostemon suaveolens": "",
    "Schefflera arboricola": "",
    "Trachycarpus fortunei": "",
    "Ligustrum lucidum": "",
    "Acer negundo Variegatum": "",
    "Acer palmatum": "",
    "Populus x canadensis Aurea": "",
    "Syncarpia glomulifera": "",
    "Eucalyptus tereticornis": "",
    "Juniperus sp.": "",
    "Ulmus procera": "",
    "Tibouchina granulosa": "",
    "Eucalyptus haemastoma": "",
    "Ficus elastica": "",
    "Albizia julibrissin Durazz": "",
    "Morus Sp.": "",
    "Morus nigra": "",
    "Michelia doltsopa": "",
    "Thuja sp.": "",
    "Cupressus macrocarpa": "",
    "Pinus sp.": "",
    "Michelia figo": "",
    "Cytisus scoparius": "",
    "Ligustrum ovalifolium Aurea": "",
    "Eucalyptus longifolia": "",
    "Eucalyptus leucoxylon Rosea": "",
    "Laurus nobilis": "",
    "Fraxinus excelsior Aurea": "",
    "Syzygium jambos": "",
    "Malus sp.": "",
    "Eucalyptus cladocalyx": "",
    "Unknown Species": "",
    "Tibouchina": "",
    "Ceratonia siliqua": "",
    "Thuja plicata": "",
    "Arbutus unedo": "",
    "Acacia longifolia": "",
    "Caesalpinia ferrea": "",
    "Persea sp.": "",
    "Archidendron mullerianum": "",
    "Ceratopetalum gummiferum": "",
    "Callitris columellaris": "",
    "Eucalyptus camaldulensis x ova": "",
    "Alphitonia excelsa": "",
    "Zelkova serrata": "",
    "Melaleuca bracteata 'Rev. Gold": "",
    "Eucalyptus leucoxylon": "",
    "Banksia sp.": "",
    "Magnolia soulangeana": "",
    "Cedrus deodara": "",
    "Banksia ericifolia": "",
    "Eucalyptus viminalis": "",
    "Phoenix sp.": "",
    "Calodendron capense": "",
    "Paulownia tomentosa": "",
    "Melicope elleryana": "",
    "Thevetia peruviana": "",
    "Davidia involucrata": "",
    "Pyrus communis": "",
    "Pinus patula": "",
    "Acacia decurrens": "",
    "Tibouchina urvilleana": "",
    "Lophostemon confertus Variegat": "",
    "Brachychiton rupestris": "",
    "Casuarina torulosa": "",
    "Rothmannia globosa": "",
    "Quercus robur": "",
    "Eucalyptus linearis": "",
    "Erythrina crista-galli": "",
}

languages = []
with open("tree_names.txt", "w", encoding="utf-8") as f:
    f.write("trees = {")
    for t in tree_name_mapping.keys():
        print(t)
        search_url = "http://api.gbif.org/v1/species/search?q="
        query = urllib.parse.quote(t)
        res = requests.get(search_url + query)
        try:
            j = res.json()
            results = j["results"]
            plants = [
                x for x in results if x.get("kingdom") in ["Viridiplantae", "Plantae"]
            ]
            has_vernacularName = [
                x for x in plants if len(x.get("vernacularNames", [])) > 0
            ]
            names = []
            for option in has_vernacularName:
                for vn in option.get("vernacularNames"):
                    lang = vn.get("language")
                    languages.append(lang)
                    if lang in ["", "eng"]:
                        names.append(vn["vernacularName"])
            name_list = [f'"{x}"' for x in names]
            f.write(f"\"{t}\":  [{', '.join(name_list)}],\n")
        except Exception as e:
            print(res.json(), e)
    f.write("}")

print(set(languages))
